[package]
name = "diesel_tests"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
build = "build.rs"
autotests = false
edition = "2018"

[build-dependencies]
diesel = { path = "../diesel", default-features = false }
diesel_migrations = { path = "../diesel_migrations" }
dotenv = ">=0.8, <0.11"

[dependencies]
assert_matches = "1.0.1"
chrono = { version = "0.4" }
diesel = { path = "../diesel", default-features = false, features = ["quickcheck", "chrono", "uuid", "serde_json", "network-address", "numeric", "with-deprecated"] }
diesel_migrations = { path = "../diesel_migrations" }
dotenv = ">=0.8, <0.11"
quickcheck = { version = "0.4", features = ["unstable"] }
uuid = { version = ">=0.7.0, <0.9.0" }
serde_json = { version=">=0.9, <2.0" }
ipnetwork = ">=0.12.2, <0.17.0"
bigdecimal = ">= 0.0.10, <= 0.1.0"

[features]
default = []
unstable = ["diesel/unstable"]
postgres = ["diesel/postgres"]
sqlite = ["diesel/sqlite"]
mysql = ["diesel/mysql"]
postgres_pure_rust = ["diesel/unstable_pure_rust_postgres"]

[[test]]
name = "integration_tests"
path = "tests/lib.rs"
harness = true

[[bench]]
name = "benchmarks"
path = "tests/bench.rs"
bench = true
